# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-03 16:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20160503_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendrequest',
            name='date_sent',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 3, 16, 33, 51, 321092)),
        ),
        migrations.AlterField(
            model_name='post',
            name='date_sent',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 3, 16, 33, 51, 321672)),
        ),
    ]
