# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-27 17:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(unique=True)),
                ('usage', models.IntegerField()),
                ('n_measurements', models.IntegerField()),
            ],
            options={
                'db_table': 'daily_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Homes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('country', models.CharField(max_length=2)),
                ('city', models.CharField(max_length=64)),
                ('zipcode', models.CharField(max_length=16)),
                ('street', models.CharField(max_length=64)),
                ('house_number', models.CharField(max_length=8)),
                ('date_added', models.DateTimeField()),
            ],
            options={
                'db_table': 'homes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='HourlyData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(unique=True)),
                ('usage', models.IntegerField()),
                ('n_measurements', models.IntegerField()),
            ],
            options={
                'db_table': 'hourly_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MonthlyData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sensor_id', models.IntegerField()),
                ('timestamp', models.DateTimeField(unique=True)),
                ('usage', models.IntegerField()),
                ('n_measurements', models.IntegerField()),
            ],
            options={
                'db_table': 'monthly_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RecentData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(unique=True)),
                ('usage', models.IntegerField()),
                ('n_measurements', models.IntegerField()),
            ],
            options={
                'db_table': 'recent_data',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sensors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=256)),
                ('power_unit', models.CharField(max_length=3)),
                ('date_created', models.DateTimeField()),
            ],
            options={
                'db_table': 'sensors',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SensorsTags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField()),
            ],
            options={
                'db_table': 'sensors_tags',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.CharField(max_length=256)),
                ('date_created', models.DateTimeField()),
            ],
            options={
                'db_table': 'tags',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UsersHomes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission_flags', models.IntegerField()),
                ('date_created', models.DateTimeField()),
            ],
            options={
                'db_table': 'users_homes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='YearlyData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(unique=True)),
                ('usage', models.IntegerField()),
                ('n_measurements', models.IntegerField()),
            ],
            options={
                'db_table': 'yearly_data',
                'managed': False,
            },
        ),
    ]
